config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  resources :posts do
    resources :comments
  end
  root "posts#index"

  get "/about", to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    if @comment.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% comments.each do |comment| %>
  <div class="comment clearfix">
    <div class="comment_content">
      <p class="comment_name"><strong><%= comment.name %></strong></p>
      <p class="comment_body"><%= comment.body %></p>
      <p class="comment_title"><%= time_ago_in_words(comment.created_at)%> ago </p>
    </div>
    <% unless !user_signed_in? %>
      <p>
        <%= link_to 'Delete', [comment.post, comment], data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "button" %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <br>

  <p>
    <%= f.submit %>
  </p>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application",
    "data-turbo-track": "reload" %>
    <%= favicon_link_tag 'favicon.png'%>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="sidebar">
      <ul>
        <li class="category"><%= link_to "Tumblr", root_path %></li>
        <li><%= link_to "Posts", root_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
      <% unless user_signed_in? %>
        <p class="sign_in"><%= link_to 'User Login', new_user_session_path %></p>
      <% end %>
    </div>
    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path)%>
          <p>Post Feed</p>
        <% elsif current_page?(about_path)%>
          <p>My Site</p>
        <% else %>
          <%= link_to 'Back to Post Feed', root_path %>
        <% end %>

        <% if user_signed_in? %>
          <div class="buttons">
            <%= link_to 'Make Post', new_post_path, class: "button" %>
            <%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "button" %>
          </div>
        <%end%>
      </div>

      <% flash.each do |name, msg|%>
        <%= content_tag(:div, msg, class: "alert") %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag 'profile.jpg' %>
  </div>
  <div id="content">
    <h1>It's Mr. Stick Figure</h1>
    <p>Same blue bottle sus ramps sustainable. Cardigan dreamcatcher butcher sriracha aesthetic four loko YOLO squid. Blog hammock wayfarers trust fund try-hard four loko kale chips tousled celiac vaporware schlitz craft beer tilde thundercats XOXO.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
      <ul>
        <%= @post.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Fix Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
  <h2 class="title"><%= link_to post.title, post %></h2>
  <p class="body"><%= truncate(post.body, length: 100) %></p>
  <p class="date"><%= time_ago_in_words(post.created_at)%> ago</p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Make something</h1>

  <%= form_with model: @post do |form| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
        <ul>
          <%= @post.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
          <%end%>
        </ul>
      </div>
    <%end%>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </div>

    <div>
      <%= form.submit %>
    </div>

  <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>
  <p class="date">
    Created: <%= time_ago_in_words(@post.created_at)%> ago
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post) %> | <%= link_to 'Delete', post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure!" } %>
    <%end%>
  </p>
  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> comments</h2>
    <%= render partial: "comments/comment", locals: { comments: @post.comments } %>
    <h3> Join Discussion: </h3>
    <%= render "comments/form" %>
  </div>
</div>